CREATE TABLE TIENDA_DIRECCION(
  CODIGO NUMBER(10) PRIMARY KEY,
  DIRECCION VARCHAR2(100) NOT NULL,
  CODIGO_POSTAL NUMBER(10) NOT NULL,
  CIUDAD VARCHAR2(50) NOT NULL,
  PROVINCIA VARCHAR2(50) NOT NULL
);

CREATE TABLE TIENDA_USUARIO (
  CODIGO NUMBER(10) PRIMARY KEY,
  EMAIL VARCHAR2(100) UNIQUE NOT NULL,
  NOMBRE VARCHAR2(50) NOT NULL,
  APELLIDO VARCHAR2(50) NOT NULL,
  CONTRASENYA VARCHAR2(100) NOT NULL,
  ULTIMA_CONEXION DATE,
  TELEFONO VARCHAR2(20),
  FECHA_NACIMIENTO DATE,
  FOTO VARCHAR2(100) DEFAULT 'GlitchSlime.webp',
  DIRECCION NUMBER(10) NOT NULL,
  TIPO VARCHAR2(10) NOT NULL CHECK (TIPO IN ('ADMIN', 'CLIENTE')),
  CONSTRAINT FK_USUARIOS_DIRECCIONES FOREIGN KEY (DIRECCION) REFERENCES TIENDA_DIRECCION(CODIGO)
);

CREATE TABLE TIENDA_PEDIDO (
  CODIGO NUMBER(10) PRIMARY KEY,
  CODIGO_USUARIO NUMBER(10) NOT NULL,
  FECHA DATE NOT NULL,
  ESTADO VARCHAR2(20) NOT NULL,
  CONSTRAINT FK_PEDIDOS_USUARIOS FOREIGN KEY (CODIGO_USUARIO) REFERENCES TIENDA_USUARIO(CODIGO)
);

CREATE TABLE TIENDA_CATEGORIA (
  CODIGO NUMBER(10) PRIMARY KEY,
  NOMBRE VARCHAR2(100) NOT NULL
);

CREATE TABLE TIENDA_PRODUCTO (
  CODIGO NUMBER(10) PRIMARY KEY,
  CODIGO_CATEGORIA NUMBER(10) NOT NULL,
  NOMBRE VARCHAR2(100) NOT NULL,
  DESCRIPCION VARCHAR2(500),
  PRECIO NUMBER(10, 2) NOT NULL,
  STOCK NUMBER(10) DEFAULT 200 NOT NULL,
  IMAGEN VARCHAR2(100) DEFAULT 'GlitchSlime.webp' NOT NULL,
  CONSTRAINT FK_PRODUCTOS_CATEGORIAS FOREIGN KEY (CODIGO_CATEGORIA) REFERENCES TIENDA_CATEGORIA(CODIGO)
);

CREATE TABLE PEDIDO_PRODUCTO (
  CODIGO_PEDIDO NUMBER(10),
  CODIGO_PRODUCTO NUMBER(10),
  CANTIDAD NUMBER(10) NOT NULL,
  CONSTRAINT PK_PEDIDO_PRODUCTO PRIMARY KEY (CODIGO_PEDIDO, CODIGO_PRODUCTO),
  CONSTRAINT FK_PEDIDO_PRODUCTO_PEDIDO FOREIGN KEY (CODIGO_PEDIDO) REFERENCES TIENDA_PEDIDO(CODIGO),
  CONSTRAINT FK_PEDIDO_PRODUCTO_PRODUCTO FOREIGN KEY (CODIGO_PRODUCTO) REFERENCES TIENDA_PRODUCTO(CODIGO)
);

CREATE TABLE TIENDA_FACTURA (
  CODIGO NUMBER(10) PRIMARY KEY,
  CODIGO_PEDIDO NUMBER(10) NOT NULL,
  FECHA DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT FK_FACTURA_PEDIDO FOREIGN KEY (CODIGO_PEDIDO) REFERENCES TIENDA_PEDIDO(CODIGO)
);

DROP TABLE TIENDA_FACTURA;

DROP TABLE PEDIDO_PRODUCTO;

DROP TABLE TIENDA_PRODUCTO;

DROP TABLE TIENDA_CATEGORIA;

DROP TABLE TIENDA_PEDIDO;

DROP TABLE TIENDA_USUARIO;

DROP TABLE TIENDA_DIRECCION;
-- CREATE SEQUENCE dept_seq START WITH 1;
-- ID  NUMBER(10) DEFAULT dept_seq.nextval NOT NULL