CREATE TABLE TIENDA_USUARIO(
    CODIGO VARCHAR2(10) PRIMARY KEY,
    EMAIL VARCHAR2(50) NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    APELLIDO VARCHAR2(50) NOT NULL,
    CONTRASENA VARCHAR2(50) NOT NULL,
    TELEFONO VARCHAR2(50),
    FOTO VARCHAR2(200),
    ULTIMA_CONEXION DATE,
    FECHA_NACIMIENTO DATE,
    TIPO VARCHAR2(10) NOT NULL CHECK (TIPO IN ('ADMIN', 'CLIENTE'))
);

CREATE TABLE TIENDA_DIRECCION(
    CODIGO VARCHAR2(10) PRIMARY KEY,
    DIRECCION VARCHAR2(200) NOT NULL,
    CODIGO_POSTAL VARCHAR2(10) NOT NULL,
    CIUDAD VARCHAR2(50) NOT NULL,
    PROVINCIA VARCHAR2(50) NOT NULL,
    CLIENTE VARCHAR2(10) NOT NULL,
    FOREIGN KEY (CLIENTE) REFERENCES TIENDA_USUARIO(CODIGO)
);

CREATE TABLE TIENDA_PEDIDOS_FACTURADOS(
    CODIGO VARCHAR2(10) PRIMARY KEY,
    FACTURA VARCHAR2(10) NOT NULL UNIQUE,
    FECHA DATE NOT NULL,
    FACTURADO VARCHAR2(10) NOT NULL,
    DIRECCION_ENVIO VARCHAR2(10) NOT NULL,
    FECHA_FACTURACION DATE NOT NULL,
    CODIGO_FACTURACION VARCHAR2(10) NOT NULL,
    CODIGO_DIRECCION VARCHAR2(10) NOT NULL,
    CLIENTE VARCHAR2(10) NOT NULL,
    FOREIGN KEY (CLIENTE) REFERENCES TIENDA_USUARIO(CODIGO),
    FOREIGN KEY (CODIGO_FACTURACION) REFERENCES TIENDA_DIRECCION(CODIGO),
    FOREIGN KEY (CODIGO_DIRECCION) REFERENCES TIENDA_DIRECCION(CODIGO)
);

CREATE TABLE TIENDA_PRODUCTOS(
    CODIGO VARCHAR2(10) PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    DESCRIPCION VARCHAR2(200) NOT NULL,
    UNIDAD VARCHAR2(10) NOT NULL,
    IVA VARCHAR2(10) NOT NULL,
    CANTIDAD_DISPONIBLE NUMBER NOT NULL,
    STOCK_MINIMO NUMBER NOT NULL,
    FOTO_PATH VARCHAR2(200),
    CREADOR VARCHAR2(10) NOT NULL,
    MODIFICADOR VARCHAR2(10) NOT NULL,
    FECHA_CREACION DATE NOT NULL,
    FECHA_MODIFICACION DATE NOT NULL,
    FOREIGN KEY (CREADOR) REFERENCES TIENDA_USUARIO(CODIGO),
    FOREIGN KEY (MODIFICADOR) REFERENCES TIENDA_USUARIO(CODIGO)
);

CREATE TABLE TIENDA_PEDIDOS_TIENEN_PRODUCTOS (
    CODIGO_PRODUCTOS VARCHAR2(10) NOT NULL,
    CODIGO_PEDIDOS VARCHAR2(10) NOT NULL,
    LIENA VARCHAR2(10) NOT NULL,
    CANTIDAD NUMBER NOT NULL,
    PRECIO NUMBER NOT NULL,
    FOREIGN KEY (CODIGO_PRODUCTOS) REFERENCES TIENDA_PRODUCTOS(CODIGO),
    FOREIGN KEY (CODIGO_PEDIDOS) REFERENCES TIENDA_PRODUCTOS(CODIGO),
    CONSTRAINT PK_PEDIDOS_TIENEN_PRODUCTOS PRIMARY KEY (CODIGO_PRODUCTOS, CODIGO_PEDIDOS)
);

CREATE TABLE TIENDA_CATEGORIAS (
    CODIGO VARCHAR2(20) PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL
);

CREATE TABLE TIENDA_CATEGORIAS_PRODUCTOS (
    CODIGO_PRODUCTOS VARCHAR2(10) NOT NULL,
    CODIGO_CATEGORIAS VARCHAR2(20) NOT NULL,
    FOREIGN KEY (CODIGO_PRODUCTOS) REFERENCES TIENDA_PRODUCTOS(CODIGO),
    FOREIGN KEY (CODIGO_CATEGORIAS) REFERENCES TIENDA_CATEGORIAS(CODIGO),
    CONSTRAINT PK_CATEGORIAS_PRODUCTOS PRIMARY KEY (CODIGO_PRODUCTOS, CODIGO_CATEGORIAS)
);
drop table tienda_categorias_productos;
drop table tienda_Categorias;
drop table tienda_pedidos_tienen_productos;
drop table tienda_productos;
drop table tienda_pedidos_facturados;
drop table tienda_direccion;
drop table tienda_usuario;
