<<<<<<< HEAD
CREATE TABLE TIENDA_USUARIO(
    CODIGO VARCHAR2(10) PRIMARY KEY,
    EMAIL VARCHAR2(50) NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    APELLIDO VARCHAR2(50) NOT NULL,
    CONTRASENA VARCHAR2(50) NOT NULL,
    TELEFONO VARCHAR2(50),
    FOTO VARCHAR2(200),
    ULTIMA_CONEXION DATE,
    FECHA_NACIMIENTO DATE,
    TIPO VARCHAR2(10) NOT NULL CHECK (TIPO IN ('ADMIN', 'CLIENTE'))
);

CREATE TABLE TIENDA_DIRECCION(
    CODIGO VARCHAR2(10) PRIMARY KEY,
    DIRECCION VARCHAR2(200) NOT NULL,
    CODIGO_POSTAL VARCHAR2(10) NOT NULL,
    CIUDAD VARCHAR2(50) NOT NULL,
    PROVINCIA VARCHAR2(50) NOT NULL,
    CLIENTE VARCHAR2(10) NOT NULL,
    FOREIGN KEY (CLIENTE) REFERENCES TIENDA_USUARIO(CODIGO)
);

CREATE TABLE TIENDA_PEDIDOS_FACTURADOS(
    CODIGO VARCHAR2(10) PRIMARY KEY,
    FACTURA VARCHAR2(10) NOT NULL UNIQUE,
    FECHA DATE NOT NULL,
    FACTURADO VARCHAR2(10) NOT NULL,
    DIRECCION_ENVIO VARCHAR2(10) NOT NULL,
    FECHA_FACTURACION DATE NOT NULL,
    CODIGO_FACTURACION VARCHAR2(10) NOT NULL,
    CODIGO_DIRECCION VARCHAR2(10) NOT NULL,
    CLIENTE VARCHAR2(10) NOT NULL,
    FOREIGN KEY (CLIENTE) REFERENCES TIENDA_USUARIO(CODIGO),
    FOREIGN KEY (CODIGO_FACTURACION) REFERENCES TIENDA_DIRECCION(CODIGO),
    FOREIGN KEY (CODIGO_DIRECCION) REFERENCES TIENDA_DIRECCION(CODIGO)
);

CREATE TABLE TIENDA_PRODUCTOS(
    CODIGO VARCHAR2(10) PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    DESCRIPCION VARCHAR2(200) NOT NULL,
    UNIDAD VARCHAR2(10) NOT NULL,
    IVA VARCHAR2(10) NOT NULL,
    CANTIDAD_DISPONIBLE NUMBER NOT NULL,
    STOCK_MINIMO NUMBER NOT NULL,
    FOTO_PATH VARCHAR2(200),
    CREADOR VARCHAR2(10) NOT NULL,
    MODIFICADOR VARCHAR2(10) NOT NULL,
    FECHA_CREACION DATE NOT NULL,
    FECHA_MODIFICACION DATE NOT NULL,
    FOREIGN KEY (CREADOR) REFERENCES TIENDA_USUARIO(CODIGO),
    FOREIGN KEY (MODIFICADOR) REFERENCES TIENDA_USUARIO(CODIGO)
);

CREATE TABLE TIENDA_PEDIDOS_TIENEN_PRODUCTOS (
    CODIGO_PRODUCTOS VARCHAR2(10) NOT NULL,
    CODIGO_PEDIDOS VARCHAR2(10) NOT NULL,
    LIENA VARCHAR2(10) NOT NULL,
    CANTIDAD NUMBER NOT NULL,
    PRECIO NUMBER NOT NULL,
    FOREIGN KEY (CODIGO_PRODUCTOS) REFERENCES TIENDA_PRODUCTOS(CODIGO),
    FOREIGN KEY (CODIGO_PEDIDOS) REFERENCES TIENDA_PRODUCTOS(CODIGO),
    CONSTRAINT PK_PEDIDOS_TIENEN_PRODUCTOS PRIMARY KEY (CODIGO_PRODUCTOS, CODIGO_PEDIDOS)
);

CREATE TABLE TIENDA_CATEGORIAS (
    CODIGO VARCHAR2(20) PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL
);

CREATE TABLE TIENDA_CATEGORIAS_PRODUCTOS (
    CODIGO_PRODUCTOS VARCHAR2(10) NOT NULL,
    CODIGO_CATEGORIAS VARCHAR2(20) NOT NULL,
    FOREIGN KEY (CODIGO_PRODUCTOS) REFERENCES TIENDA_PRODUCTOS(CODIGO),
    FOREIGN KEY (CODIGO_CATEGORIAS) REFERENCES TIENDA_CATEGORIAS(CODIGO),
    CONSTRAINT PK_CATEGORIAS_PRODUCTOS PRIMARY KEY (CODIGO_PRODUCTOS, CODIGO_CATEGORIAS)
);
=======
CREATE TABLE TIENDA_DIRECCION(
  codigo NUMBER(10) PRIMARY KEY,
  direccion VARCHAR2(100) NOT NULL,
  codigo_postal VARCHAR2(10) NOT NULL,
  ciudad VARCHAR2(50) NOT NULL,
  provincia VARCHAR2(50) NOT NULL
);

CREATE TABLE TIENDA_USUARIO (
  codigo NUMBER(10) PRIMARY KEY,
  email VARCHAR2(100) UNIQUE NOT NULL,
  nombre VARCHAR2(50) NOT NULL,
  apellido VARCHAR2(50) NOT NULL,
  contraseña VARCHAR2(100) NOT NULL,
  ultima_conexion DATE,
  telefono VARCHAR2(20),
  fecha_nacimiento DATE,
  foto VARCHAR2(100),
  direccion NUMBER(10) NOT NULL,
  tipo VARCHAR2(10) NOT NULL CHECK (TIPO IN ('ADMIN', 'CLIENTE'))
  CONSTRAINT fk_usuarios_direcciones FOREIGN KEY (direccion) REFERENCES TIENDA_DIRECCION(codigo)
);

CREATE TABLE TIENDA_PEDIDO (
  codigo NUMBER(10) PRIMARY KEY,
  codigo_usuario NUMBER(10) NOT NULL,
  fecha DATE NOT NULL,
  estado VARCHAR2(20) NOT NULL,
  CONSTRAINT fk_pedidos_usuarios FOREIGN KEY (codigo_usuario) REFERENCES TIENDA_USUARIO(codigo)
);

CREATE TABLE TIENDA_CATEGORIA (
  codigo NUMBER(10) PRIMARY KEY,
  nombre VARCHAR2(100) NOT NULL
);

CREATE TABLE TIENDA_PRODUCTO (
  codigo NUMBER(10) PRIMARY KEY,
  codigo_categoria NUMBER(10) NOT NULL,
  nombre VARCHAR2(100) NOT NULL,
  descripcion VARCHAR2(500),
  precio NUMBER(10,2) NOT NULL,
  stock NUMBER(10) NOT NULL,
  imagen VARCHAR2(100),
  CONSTRAINT fk_productos_categorias FOREIGN KEY (codigo_categoria) REFERENCES TIENDA_CATEGORIA(codigo)
);

CREATE TABLE PEDIDO_PRODUCTO (
  codigo_pedido NUMBER(10),
  codigo_producto NUMBER(10),
  cantidad NUMBER(10) NOT NULL,
  CONSTRAINT pk_pedido_producto PRIMARY KEY (codigo_pedido, codigo_producto),
  CONSTRAINT fk_pedido_producto_pedido FOREIGN KEY (codigo_pedido) REFERENCES TIENDA_PEDIDO(codigo),
  CONSTRAINT fk_pedido_producto_producto FOREIGN KEY (codigo_producto) REFERENCES TIENDA_PRODUCTO(codigo)
);

CREATE TABLE TIENDA_FACTURA (
  codigo NUMBER(10) PRIMARY KEY,
  codigo_pedido NUMBER(10) NOT NULL,
  fecha DATE NOT NULL,
  CONSTRAINT fk_factura_pedido FOREIGN KEY (codigo_pedido) REFERENCES TIENDA_PEDIDO(codigo)
);

>>>>>>> dev
drop table tienda_categorias_productos;
drop table tienda_Categorias;
drop table tienda_pedidos_tienen_productos;
drop table tienda_productos;
drop table tienda_pedidos_facturados;
drop table tienda_direccion;
<<<<<<< HEAD
drop table tienda_usuario;
=======
drop table tienda_usuario;
>>>>>>> dev
