
-- Usuarios

INSERT INTO TIENDA_USUARIO 
    (CODIGO,EMAIL,NOMBRE,APELLIDO,CONTRASENA,TIPO)
VALUES (1,'ivanAyusoOlivera.alu@iespacomolla.es','Ivan','Ayuso','presidentaDeMadrid2023','ADMIN');

INSERT INTO TIENDA_USUARIO 
    (CODIGO,EMAIL,NOMBRE,APELLIDO,CONTRASENA,TIPO)
VALUES (2,'dianaSoriano.alu@iespacomolla.es','Diana','Soriano','PequeñoDemonioInfernal2023','ADMIN');

INSERT INTO TIENDA_USUARIO 
    (CODIGO,EMAIL,NOMBRE,APELLIDO,CONTRASENA,TIPO)
VALUES (3,'isaacJulianPavon.alu@iespacomolla.es','Isaac','Pavon','tanuki2023','CLIENTE');


-- Direcciones

INSERT INTO TIENDA_DIRECCION
    (CODIGO,DIRECCION,CODIGO_POSTAL,CIUDAD,PROVINCIA,CLIENTE)
VALUES (1,'calle medico rafael navarro', 03660, 'NOVELDA', 'ALICANTE', 1);

INSERT INTO TIENDA_DIRECCION
    (CODIGO,DIRECCION,CODIGO_POSTAL,CIUDAD,PROVINCIA,CLIENTE)
VALUES (2,'calle infierno 666', 03400, 'VILLENA', 'ALICANTE', 2);

INSERT INTO TIENDA_DIRECCION
    (CODIGO,DIRECCION,CODIGO_POSTAL,CIUDAD,PROVINCIA,CLIENTE)
VALUES (3,'calle chile 1 bajo derecha', 03600, 'ELDA', 'ALICANTE', 3);

-- PRODUCTOS FACTURADOS 

INSERT INTO TIENDA_PEDIDOS_FACTURADOS
    (CODIGO,FACTURA,FECHA,FACTURADO,DIRECCION_ENVIO,FECHA_FACTURACION,CODIGO_FACTURACION,CODIGO_DIRECCION,CLIENTE)
VALUES(1,1,SYSDATE,'si','calle',SYSDATE,3,3,3);

INSERT INTO TIENDA_PEDIDOS_FACTURADOS
        (CODIGO,FACTURA,FECHA,FACTURADO,DIRECCION_ENVIO,FECHA_FACTURACION,CODIGO_FACTURACION,CODIGO_DIRECCION,CLIENTE)
VALUES(2,2,SYSDATE,'si','calle',SYSDATE,3,3,3);

INSERT INTO TIENDA_PEDIDOS_FACTURADOS
        (CODIGO,FACTURA,FECHA,FACTURADO,DIRECCION_ENVIO,FECHA_FACTURACION,CODIGO_FACTURACION,CODIGO_DIRECCION,CLIENTE)
VALUES(3,3,SYSDATE,'si','calle',SYSDATE,3,3,3);

-- TIENDA_PRODUCTOS

INSERT INTO TIENDA_PRODUCTOS
    (CODIGO,NOMBRE,DESCRIPCION,UNIDAD,IVA,CANTIDAD_DISPONIBLE,STOCK_MINIMO,CREADOR,MODIFICADOR,FECHA_CREACION,FECHA_MODIFICACION)
VALUES(1,'rosa','port del slime rosa','port','21',500,5,1,1,SYSDATE,SYSDATE);


INSERT INTO TIENDA_PRODUCTOS
    (CODIGO,NOMBRE,DESCRIPCION,UNIDAD,IVA,CANTIDAD_DISPONIBLE,STOCK_MINIMO,CREADOR,MODIFICADOR,FECHA_CREACION,FECHA_MODIFICACION)
VALUES(2,'roca','port del slime roca','port','21',500,5,1,1,SYSDATE,SYSDATE);

INSERT INTO TIENDA_PRODUCTOS
    (CODIGO,NOMBRE,DESCRIPCION,UNIDAD,IVA,CANTIDAD_DISPONIBLE,STOCK_MINIMO,CREADOR,MODIFICADOR,FECHA_CREACION,FECHA_MODIFICACION)
VALUES(3,'fosforo','port del slime fosforo','port','21',500,5,2,2,SYSDATE,SYSDATE);

-- TIENDA_PEDIDOS_TIENEN_PRODUCTOS

INSERT INTO TIENDA_PEDIDOS_TIENEN_PRODUCTOS
    (CODIGO_PRODUCTOS,CODIGO_PEDIDOS,LIENA,CANTIDAD,PRECIO)
VALUES(1,1,1,200,4);
INSERT INTO TIENDA_PEDIDOS_TIENEN_PRODUCTOS
    (CODIGO_PRODUCTOS,CODIGO_PEDIDOS,LIENA,CANTIDAD,PRECIO)
VALUES(2,1,1,100,4);
INSERT INTO TIENDA_PEDIDOS_TIENEN_PRODUCTOS
    (CODIGO_PRODUCTOS,CODIGO_PEDIDOS,LIENA,CANTIDAD,PRECIO)
VALUES(2,3,1,365,8);


-- TIENDA CATEGORIAS

INSERT INTO TIENDA_CATEGORIAS
    (CODIGO, NOMBRE)
VALUES(1,'rosa');
INSERT INTO TIENDA_CATEGORIAS
    (CODIGO, NOMBRE)
VALUES(2,'roca');
INSERT INTO TIENDA_CATEGORIAS
    (CODIGO, NOMBRE)
VALUES(3,'fosforo');

-- TIENDA_CATEGORIAS_PRODUCTOS

INSERT INTO TIENDA_CATEGORIAS_PRODUCTOS
    (CODIGO_PRODUCTOS, CODIGO_CATEGORIAS)
VALUES (1,1);

INSERT INTO TIENDA_CATEGORIAS_PRODUCTOS
    (CODIGO_PRODUCTOS, CODIGO_CATEGORIAS)
VALUES (2,2);

INSERT INTO TIENDA_CATEGORIAS_PRODUCTOS
    (CODIGO_PRODUCTOS, CODIGO_CATEGORIAS)
VALUES (3,3);

UPDATE TIENDA_DIRECCION SET direccion = 'San fernando 62' WHERE codigo =2;
UPDATE TIENDA_PRODUCTOS SET descripcion = 'del slime rosa' WHERE codigo =1;
UPDATE TIENDA_PEDIDOS_TIENEN_PRODUCTOS SET cantidad = 500 WHERE CODIGO_PRODUCTOS =1;

DELETE FROM TIENDA_CATEGORIAS_PRODUCTOS WHERE CODIGO_PRODUCTOS = '3';
DELETE FROM TIENDA_CATEGORIAS_PRODUCTOS WHERE CODIGO_PRODUCTOS = '1';
